FROM python:3.11-slim

WORKDIR /app
COPY viewer/ /app/viewer/
WORKDIR /app/viewer

RUN pip install --no-cache-dir -e .[dev]

ENV HOST=0.0.0.0
ENV PORT=8080

CMD ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
